{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nomad.serviceAccountName" . }}
  namespace: {{ include "nomad.namespace" . }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
{{- end }}
