apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name }}
  namespace: {{ include "nomad.namespace" . }}
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 4646
    targetPort: 4646
    protocol: TCP
  - name: rpc
    port: 4647
    targetPort: 4647
    protocol: TCP
  - name: serf
    port: 4648
    targetPort: 4648
    protocol: TCP
  selector:
    {{- include "nomad.selectorLabels" . | nindent 4 }}
