apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.internal.name }}
  namespace: {{ include "nomad.namespace" . }}
  annotations:
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.internal.type }}
  ports:
  - name: http
    port: {{ .Values.service.internal.port }}
    targetPort: 4646
    protocol: TCP
  selector:
    {{- include "nomad.selectorLabels" . | nindent 4 }}
